import { UserRole } from "@/generated/prisma/browser";
import { PERMISSIONS } from "./permisions";

export const ROLE_PERMISSIONS: Record<UserRole, string[]> = {
  SUPER_ADMIN: ["*"],

  ADMIN: [
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,

    PERMISSIONS.DRUG_VIEW,
    PERMISSIONS.DRUG_CREATE,
    PERMISSIONS.DRUG_UPDATE,

    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_RECEIVE,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.INVENTORY_TRANSFER,

    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_APPROVE,

    PERMISSIONS.REPORT_VIEW,

    PERMISSIONS.NOTIFICATION_VIEW,

    PERMISSIONS.AUDIT_VIEW,
  ],

  PHARMACIST: [
    PERMISSIONS.DRUG_VIEW,
    PERMISSIONS.DRUG_CREATE,
    PERMISSIONS.DRUG_UPDATE,

    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_RECEIVE,
    PERMISSIONS.INVENTORY_ADJUST,

    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_CREATE,

    PERMISSIONS.REPORT_VIEW,

    PERMISSIONS.NOTIFICATION_VIEW,
  ],

  STAFF: [
    PERMISSIONS.DRUG_VIEW,

    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_RECEIVE,

    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_CREATE,

    PERMISSIONS.NOTIFICATION_VIEW,
  ],

  VIEWER: [
    PERMISSIONS.DRUG_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.NOTIFICATION_VIEW,
  ],
};